### PR TITLE
Apply move cleanup

### PR DESCRIPTION
**Pull request by lucasart**

### CODE REVIEW

**Comment by AndyGrant** [comment]
This is about a 1% slow down for me. But I think removing 100LOC is worth that speed drop.

Also, I'm not sure where you are looking to go from here ... but it looks like you are planning on moving ``Zobrist[32][SQUARE_NB] -> Zobrist[COLOUR_NB][PIECE_NB][SQUARE_NB]``, and perhaps something similar for the ``PawnKingZobrist``, which has the potential to bring some speed back.

EDIT: Same goes for ``PSQT``, since you are now always getting a colour and piece AFAIK

**Comment by lucasart** [comment]
My first plan is to apply the same to revertMove(). Then I will do some speed measures. But to do reliable speed measures, you need bench from command line, not UCI mode. That's because stdout printing causes lots of noise, and you need to silence it by redirecting stdout to /dev/null (and print only the final result in stderr, SF trick). I will also check GCC vs. Clang here. In my experience, GCC is not so good at inlining across compilation units with LTO. Clang might be faster here. Let me finish that first, and I will post results.

**Comment by AndyGrant** [comment]
``undo->castlePiece`` can be ``EMPTY``, which has ``colour=BLACK+1`` and ``piece=KING+1``.
I have room in the bitboards for looking up with those values, but the assertions you have are hit.

**Comment by lucasart** [comment]
Thanks. I'll have a look. This is still very much work in progress.

**Comment by lucasart** [comment]
Patch is ready, in terms of correctness. I'll have a look at speed later...

**Comment by AndyGrant** [comment]
Speed difference is even larger now.

Two compiler warnings since ``Undo *undo`` is now unused in two move apply functions

Removing the void pointer function call crap might net some speed back, I suspect.

**Comment by AndyGrant** [comment]
I don't think you'll be able to keep the speed like this. Current master certainly has too many lines for the content, but grouping the updated variables together is very fast. I've not looked at an assembly dump, but I expect the compiler cannot know to combine, for example, all of the colour updates for castling into one xor. Likewise, I'm guessing that the PSQT and Zobrist hits are not ordered together, which adds some extra movs and cache usage. 

Also, removing key updates and psqt/material from the Undo struct is just begging for a slow down. I've tried moving the psqt+mat computation to the actual evaluation, and even that is a slow down. 

I'm torn because 1) You've written some nice code, 2) I love cutting out unnecessary lines of code, and 3) What you have written is very clear to an outside reader. On the other side, is it worth slowing down my a measurable amount? Am I just a mad man looking for absurd micro-optimizations?

**Comment by lucasart** [comment]
I'll have a look at this tonight, to see if I can bring some speed back. But I refuse to accept that code has to be ugly and complicated to be fast. Have faith, we'll find a way.

**Comment by lucasart** [comment]
I guess what I'm trying to say is:
* Don't commit this PR for the moment. There's no hurry, and you don't have to choose between elegance and speed. You'll get both, in time.
* Meanwhile, please avoid doing gratuitous code changed (like indentations, deleting empty lines etc.) that interfere with this PR. I noticed you have a bad habit of mixing patches with hundreds of gratuitous diff for code style massage. This will create non trivial merge conflicts, which is annoying.

**Comment by lucasart** [comment]
Compilers may be smarter than you think. In theory, the compiler is able to inline across compilation units (thanks to LTO) the clearSquare() and setSquare() calls, the reorder as the compiler sees fit. What the compiler can't do (forbidden by C standard) is reorder struct elements though, so maybe I can play with that.

It may be worth experimenting with PGO now, to see if it allows the compiler to be smarter.

**Comment by AndyGrant** [comment]
Okay. I'll note that I've never had much luck with PGO. Only one machine of mine has a faster PGO build than standard.

> I noticed you have a bad habit of mixing patches with hundreds of gratuitous diff for code style massage.

Your first patches removed trailing white space. Since then I have set my editor to remove that when I save. Therefore each time I have touched a new file in a commit, those changes are made. I have no plans for anything dealing with ``move`` and ``board`` at the moment.

**Comment by lucasart** [comment]
How about now ? I rewrote the commit history of the branch to show only 2 patches:
* first one is the fully high-level solution (`1%` slowdown using clang).
* second one restores most of the speed loss, by using low-level for applying normal moves.

**Comment by AndyGrant** [comment]
I get much more than ``1%`` with GCC, which also produces much faster compiles than Clang for me.
I get ``-1.3%`` on the second version. I will need to think about this for a while.

**Comment by lucasart** [comment]
Let's keep this one on hold for now. I will prepare another PR to allow more accurate and precise speed measures.

**Comment by lucasart** [comment]
Using the new bench branch, I measured the following, with GCC compiles:
```
lucas@megatron:~/Chess/Ethereal/src$ ./bench bench 17 | tail -1
NPS   : 3224329
lucas@megatron:~/Chess/Ethereal/src$ ./bench bench 17 | tail -1
NPS   : 3197535
lucas@megatron:~/Chess/Ethereal/src$ ./bench bench 17 | tail -1
NPS   : 3209506
lucas@megatron:~/Chess/Ethereal/src$ ./bench bench 17 | tail -1
NPS   : 3199210
lucas@megatron:~/Chess/Ethereal/src$ ./bench bench 17 | tail -1
NPS   : 3214361
lucas@megatron:~/Chess/Ethereal/src$ ./measure bench 17 | tail -1
NPS   : 3189813
lucas@megatron:~/Chess/Ethereal/src$ ./measure bench 17 | tail -1
NPS   : 3197326
lucas@megatron:~/Chess/Ethereal/src$ ./measure bench 17 | tail -1
NPS   : 3185239
lucas@megatron:~/Chess/Ethereal/src$ ./measure bench 17 | tail -1
NPS   : 3192313
lucas@megatron:~/Chess/Ethereal/src$ ./measure bench 17 | tail -1
NPS   : 3201935
```
So the median of these 5 runs is:
```
lucas@megatron:~/Chess/Ethereal/src$ ./bench bench 17 | tail -1
NPS   : 3209506

lucas@megatron:~/Chess/Ethereal/src$ ./measure bench 17 | tail -1
NPS   : 3197326
```
Which means we are only 0.4% slower.

To recover the speed loss, it seems we must do the same with revertMove(). Write low-level code for the hot path (NORMAL_MOVE) and keep high-level for the cold path.

**Comment by lucasart** [comment]
> To recover the speed loss, it seems we must do the same with revertMove(). Write low-level code for the hot path (NORMAL_MOVE) and keep high-level for the cold path.

I tried that, including resore psqtmat/pkhash from undo, but it didn't gain any speed. So the current state of this PR is the best compromise I can get. To restore the 0.4% slowdown, we have to uglify the whole lot, it seems (ie. keep master as is).

**Comment by AndyGrant** [comment]
Alright. Let me take another look. Likely will merge, and change any styling with a patch I'm about to push.
Assuming I can confirm similar speed numbers. anything less than 1% is commit-able in my mind now.

**Comment by AndyGrant** [comment]
Perft testing shows a different story (clearly highlights applyMove and revertMove)
``test: 245740ms``
``base: 218839ms``
I know you've put a lot of time into this, but I'm still not too excited about merging.

**Comment by AndyGrant** [comment]
```
Andy@PowerHouse MINGW64 ~/Desktop/Github/Ethereal/src (master)
$ ./Ethereal.exe bench 24 | tail -n 3
Time  : 235873ms
Nodes : 592877413
NPS   : 2513545

Andy@PowerHouse MINGW64 ~/Desktop/Github/Ethereal/src (master)
$ ./Ethereal.exe bench 24 | tail -n 3
Time  : 235936ms
Nodes : 592877413
NPS   : 2512873

Andy@PowerHouse MINGW64 ~/Desktop/Github/Ethereal/src (master)
$ ./Ethereal.exe bench 24 | tail -n 3
Time  : 235873ms
Nodes : 592877413
NPS   : 2513545
```
```
Andy@PowerHouse MINGW64 ~/Desktop/src
$ ./Ethereal.exe bench 24 | tail -n 3
Time  : 240257ms
Nodes : 592877413
NPS   : 2467680

Andy@PowerHouse MINGW64 ~/Desktop/src
$ ./Ethereal.exe bench 24 | tail -n 3
Time  : 240210ms
Nodes : 592877413
NPS   : 2468162

Andy@PowerHouse MINGW64 ~/Desktop/src
$ ./Ethereal.exe bench 24 | tail -n 3
Time  : 239836ms
Nodes : 592877413
NPS   : 2472011
```

I still get the 1.5+% slowdown. Similar results on my main Linux box.

**Pull request closed without merging**
