### PR TITLE
Correct singular keys (9385381)

### PR DESCRIPTION
**Pull request by lucasart**
Can you try this on your framework ?

I can't really test it, because singular only kicks in at high depth, so is only mesurable at long tc. and with my puny testing resources (just a quad), it would either take for ever, or i'd have to sacrifice testing resolution...

On the one hand, this is more theoretically correct. But on the other hand, even with wrong tt hit, we could still have a benefit to to improved move ordering etc. So it's not clear where the tradeoff lies.

### CODE REVIEW

**Comment by lucasart** [comment]
First patch was wrong. Just pushed a fix. Bench should be 9433105.

**Comment by AndyGrant** [comment]
I will try this, but I think you may be thinking more towards what Stockfish does.

Stockfish recalls search(), but with an excluded move set. Thus a new key is needed. Since Ethereal is simply trying each non-tt move on it's own, no new key is needed.

**Comment by lucasart** [comment]
You're right. Patch is pointless. Sorry.

**Comment by AndyGrant** [comment]
```
SPRT @ 5.0+0.05s Threads=1 Hash=8MB
LLR: -1.70 (-2.20, 2.20) [0.00, 5.00]
Games: 2650 W: 567 L: 630 D: 1453
``` 

Stopped early.

**Comment by AndyGrant** [comment]
Worth noting that I have tried to do the SF method -- and been unsuccessful so far. There should be elo there from pruning some of the moves instead of proving them to not beat the rBeta defined by the table move.

**Pull request closed without merging**
