### PR TITLE
Bitutils code-style massage

### PR DESCRIPTION
**Pull request by lucasart**
No functional change.

### CODE REVIEW

**Comment by AndyGrant** [comment]
I think you unintentionally dropped support for non-popcount by removing countSetBits(), which populates BitCounts. Suppose the cleaner way is to make countSetBits() a static function of magics.c.

I have nothing for or against moreThanOne -> several.

And then same deal as bitboards PR, I'm doing the brace on the same line, no space before the brace for ifs, fors, whiles, functions, ...  , .

I would be happy to merge this + the bitboards PR if you adjust the things I mentioned. And might as well convert everything to use pragma once in one fell swoop, unless you plan on doing this code-style for each file.

**Comment by lucasart** [comment]
> I think you unintentionally dropped support for non-popcount by removing countSetBits(), which populates BitCounts. Suppose the cleaner way is to make countSetBits() a static function of magics.c.

Indeed. I fixed by dropping USE_POPCOUNT completely. You don't need conditional compilation here. It's the compiler's job to figure out what to do with `__builtin_popcountll()`: if the target architecture has hardware popcount use it, if not use software fallback. So you can use the software fallback generated by the compiler, instead of writing your own.

> And then same deal as bitboards PR, I'm doing the brace on the same line, no space before the brace for ifs, fors, whiles, functions, ... , .

brace on same line as function header => done.
no space before the brace for ifs, fors, whiles, functions => sorry, I can't get used to that. if you insist, i'll do it, but it hurts my eyes, and is against feng shui principles ;-)

> And might as well convert everything to use pragma once in one fell swoop, unless you plan on doing this code-style for each file.

I'd rather work one unit at a time for now (ie. xxx.h / xxx.c) and keep pull request small and localized. pragma once, or space between `)` and `{` is like a code marker. It's a way to know where I've been. Don't worry, I plan to do more than trivial code refactoring. But I have to start slowly, and see if you like it.

**Comment by lucasart** [comment]
commit updated. please check.

**Comment by AndyGrant** [comment]
I figured you would say that about popcount, I recall this exact conversation in a talkchess thread. 
My reason for avoiding it was so that I could easily build non-popcount binaries from my dev machine without having to worry about setting march equal to some "old enough" arch.

If you know of a generalized way to have the makefile assume a non-popcount arch [here](https://github.com/lucasart/Ethereal/blob/444dbffd953f0021467be224170b20ac43b7c362/src/makefile#L56) then I would be happy to remove the conditional compile.

Also, why ``*bb &= *bb - 1;`` Over ``*bb ^= 1ull << lsb;``

Compared the two asm outputs, your way uses 2 mov, 1 sub, 1 and, my way uses 4 move, 1 shl, 1 xor. So that is fine. No "why" needs answering ...

Happy with everything else. I said I would embrace the coding style you want in the other commit, restating.

**Comment by lucasart** [comment]
You needn't use march for release compiles. Simply use `-mpopcnt` for popcnt compiles, and omit it otherwise. It's an opt-in feature, not opt-out.

**Comment by lucasart** [comment]
But if you insist on keeping a home grown software popcount, may I suggest a SWAR popcount instead ? It's at least as fast, and it's cleaner because it doesn't require any precomputed data (which helps reduce the unnatural intertwining of `bitboard.*` and `magics.*`).

**Comment by AndyGrant** [comment]
And again you are correct. I'll look at this again and merge when I get a chance this evening.
You are right, there is no reason for a software popcount. 
Now that I think about it, you pushed for the same thing in Stockfish recently, yes?

**Comment by lucasart** [comment]
Thanks. After that I will work on magics, which needs some love.

By the way, K&R style is to put the brace on the same line (with a space), *except* for functions.

**Comment by AndyGrant** [comment]
Magics have been left untouched for quite some time. That is some of the first C I ever wrote, so that might be quite ugly. 

Thanks for your efforts here. I highly value anything that increases readability, maintainability, or just general removes excess code.

Why the sudden interest in Ethereal?

**Pull request merged**
