### PR TITLE
Implement Chess960

### PR DESCRIPTION
**Pull request by lucasart**
Work in progress:
- perft passed
- bench failed (different node count)
- moveIsPseudoLegal(): rewrite with castleRooks representation
- tb_probe_root(): not sure what to do there
- UCI_Chess960 option
- display e1h1 when UCI_Chess960=true
- change perft test suite to include Chess960 positions

### CODE REVIEW

**Comment by AndyGrant** [comment]
Not much time to look right now ....
I don't think Syzygy works with castle rights ... 
Therefore we can just pass ``0b0000`` instead of ``board->castleRights`` ?

**Comment by lucasart** [comment]
> bench failed (different node count)

Turns out there is *probably* no bug here (to be confirmed). The fact that the entire perft test suite passed is already a strong hint that it works. What happens is that the zobrist hashing is incompatible by design between FRC and master:
* FRC combines like this: `ZobristCastle[A1] | ZobristCastle[H1]` (meaning white has both OO and OOO).
* master used: `ZobristKeys[CASTLE][WHITE_QUEEN_CASTLE | WHITE_KING_CASTLE]`. This is not equal to `ZobristKeys[CASTLE][WHITE_QUEEN_CASTLE] | ZobristKeys[CASTLE][WHITE_KING_CASTLE]`. So I am going to have to patch master (in another branch) to make them equal, as well as all 16 possible combinations of castling rights, to be able to compare bench numbers between FRC and master.

**Comment by lucasart** [comment]
> Therefore we can just pass 0b0000 instead of board->castleRights ?

Yes, that will make my life much easier. I really don't want to delve into this hidious syzygy code...

**Comment by AndyGrant** [comment]
Not sure if that is a slam on me, fathom , or syzygy, ..., But the only reason it it there is for completeness and TCEC.

For example, mate finding is broken with TB on, but no one cares.

**Comment by lucasart** [comment]
The slam is on syzygy. This code is a serious contender for the IOCCC.

**Comment by lucasart** [comment]
You're putting the carriage in front of the horse. It's too early to talk about speed.
- First, I need to rewrite the castling part of moveIsPseudoLegal() using the new representation, keeping the old one to check at run time that both functions always return the same result.
- Then I need to verify functional parity with master by changing the zobrist castling logic in master, to make the comparison even possible.
- Then I can remove all the old castling code.
- Only then we can measure speed. Right now we'd be comparing apples and oranges.

And even then, it's not ready to merge. There are a few more things to do:
- parse Shredder FEN
- introduce UCI_Chess960 option
- use e1h1 notation in Chess960 (mandated by UCI)
- change bench.csv to include some Chess960 positions, using both normal and Shredder FEN.
- ditto with perft.epd (and change perft.py to set UCI_Chess960 option).

**Comment by lucasart** [comment]
The 'uci.c' code desperately needs a rewrite… But for now, I try to keep the diff minimal and focused only on Chess960. So I will just hack moveToString() to use e1h1 notation in Chess960.

Eventually we may want proper parsing code (ie. strtok_r()), and stringToMove() rather than generating all moves and comparing the token to moveToString().

**Comment by AndyGrant** [comment]
I'm fairly happy with the state of ``uci.c`` as is, aside from what you have just mentioned. What about it do you find so horrid?

**Comment by lucasart** [comment]
Have you ever done functional programming ? (eg. Haskell or Caml). It helps to understand what I mean by proper parser.

Conceptually you should parse as follows:
- parse: s -> (head, tail), where head is the first token, and tail is the rest of the string. you have that function already in strtok_r().
- no pointer arithmetic, no assumptions that there is exactly one space between tokens. everything should be expressed recursively.

**Comment by AndyGrant** [comment]
I have no interest in such an implementation.

**Comment by AndyGrant** [comment]
Moved to https://github.com/AndyGrant/Ethereal/tree/ethereal_frc , likely finished. A good chunk of what you wrote was useful, but a fair amount hinged on encoding castle moves as KxR, which Ethereal does not do. Added some bits to signify which side the castle is towards to replace what KxR encoding solved.

**Pull request closed without merging**
