### PR TITLE
FEN parser: in progress

### PR DESCRIPTION
**Pull request by lucasart**
Work in progress, not mergeable yet (not finished, not fully tested). Please have a look and let me know what you think of it.

### CODE REVIEW

**Comment by AndyGrant** [comment]
Only thing I don't like is the for loop to determine piece colour.

As an aside, ``PawnKingKeys`` is zero'ed on for all non pawn or king entries. I've tried to do things similar to your ``setSquare()`` in terms of updating pkhash conditionally, but those are always slow downs. Maybe it  is time to revisit it. ``PawnKingKeys`` wastes a lot of cache.

**Comment by lucasart** [comment]
Finished the patch. It seems to work.

**Comment by lucasart** [comment]
> Only thing I don't like is the for loop to determine piece colour.

Agreed. Fixed.

> As an aside, PawnKingKeys is zero'ed on for all non pawn or king entries. I've tried to do things similar to your setSquare() in terms of updating pkhash conditionally, but those are always slow downs. Maybe it is time to revisit it. PawnKingKeys wastes a lot of cache.

PawnKingKeys is totally useless. Since pkhash and hash are orthogonal by design, you can reuse ZorbistKeys for pkhash. And, by the way, It's Zobrist, not Zorbist. But I'm not touching that for the moment. There are many more things to do before we can fix all that.

**Comment by AndyGrant** [comment]
Need to factor in the enpass square and the castle zobrist . Also, I spelled zorbrist wrong it seems.

Also, even if the last move was a double pawn move, I don't set ``board->epSquare`` unless we have a pawn lined up to capture it. So that needs to be accounted for in ``setupBoard``, or removed altogether and tested as a simplification.

**Comment by lucasart** [comment]
> Need to factor in the enpass square and the castle zobrist . Also, I spelled zorbrist wrong it seems.

Done: 7065990ea5f9ff691d96a2a0dbbdc89cba313bf8.

> Also, even if the last move was a double pawn move, I don't set board->epSquare unless we have a pawn lined up to capture it. So that needs to be accounted for in setupBoard, or removed altogether and tested as a simplification.

Will do.

**Comment by lucasart** [comment]
Can you merge the other PR so I can rebase ?

**Comment by AndyGrant** [comment]
Yes.
The commit you linked does not deal with what I said?

**Comment by lucasart** [comment]
how about not?

**Comment by AndyGrant** [comment]
Think the only thing left is to only enpass square when there is a pawn in place to perform this capture.

In theory, this does a better job of hashing positions in the TT, since if no enpass is possible despite a pawn double move, we have access to many other transpositions.

If you think this makes sense, then let us do it. Otherwise, I will launch a test to verify the simplification.

**Comment by lucasart** [comment]
> In theory, this does a better job of hashing positions in the TT, since if no enpass is possible despite a pawn double move, we have access to many other transpositions.

I know. I used to do that in Demolito, and realised it was useless, so removed it.

> If you think this makes sense, then let us do it. Otherwise, I will launch a test to verify the simplification.

You're right. The correct approach is to first code iso-functional. Then test functional change. Even if this is a tiny one, which I "know" is harmless. I will reintroduce your en passant trick.

**Comment by AndyGrant** [comment]
Also, I believe this explains why the enpass parsing was broken?

**Comment by AndyGrant** [comment]
```
SPRT @ 5.0+0.05s Threads=1 Hash=8MB
LLR: -1.65 (-2.20, 2.20) [-4.00, 0.00]
Games: 3900 W: 841 L: 950 D: 2109 
```
Partial results, but it looks like this is important. I can think of a number of ways to write it better. 
Could simple use [this](https://github.com/AndyGrant/Ethereal/blob/master/src/movegen.c#L48) as a test

**Comment by lucasart** [comment]
How do you run your tests ?
* if you use a book, the engine receives `position startpos moves…`, so this canot have any impact.
* if you use `position fen …` with no `moves …`, then there is an impact. But it cannot possibly be mesurable. At worst 1 position out of tens of billions is affected in the rare case where the start fen has an unusable epsq. So we're talking 1 in hundreds of millions impact.

If there is any elo value in this enpass trick, it can only be in applyMove(), not in setBoard().

**Comment by AndyGrant** [comment]
I'm running my own version of fishtesh, which passes 2moves_v1.pgn to cutechess.
I tested by removing the trick from both ``setBoard()`` and ``applyMove()``, which is why the difference is noticeable.

**Comment by lucasart** [comment]
But this is the problem. If you leave applyMove() untouched, and test only this PR, you will see zero impact.

**Comment by AndyGrant** [comment]
Okay , but for consistency don't we want the trick in all places ?

**Comment by lucasart** [comment]
I don't think so. It has no value in setBoard() and complicates code, so I'd rather not add it there.

**Comment by lucasart** [comment]
I'd like to add the inverse function of setBoard(): get FEN string from board position. It's just a debug function, not used in UCI mode. OK for you ?

**Comment by AndyGrant** [comment]
FEN string is fine. I've been meaning to do that myself. 

I'll concede ``setBoard()``, since Ethereal never reads a fen in actual games AFAIK.

**Comment by lucasart** [comment]
Added another patch, to display checkers.

I'm not printing other info like: side to move, 50 move counter, castling rights, en passant square.

I will do that by simply printing the FEN. But first I need to compute the FEN. So, in the end, it will look like this:
```
  |---|---|---|---|---|---|---|---|
8 | r | n | b | . | k | . | n | r |
  |---|---|---|---|---|---|---|---|
7 | p | p | p | . | . | p | p | p |
  |---|---|---|---|---|---|---|---|
6 | . | . | . | b | . | . | . | . |
  |---|---|---|---|---|---|---|---|
5 | . | . | . | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
4 | . | . | . | . | . | . | . | q |
  |---|---|---|---|---|---|---|---|
3 | . | . | N | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
2 | P | P | P | P | P | . | P | P |
  |---|---|---|---|---|---|---|---|
1 | R | . | B | Q | K | B | N | R |
  |---|---|---|---|---|---|---|---|
    A   B   C   D   E   F   G   H
fen: rnb1k1nr/ppp2ppp/3b4/8/7q/2N5/PPPPP1PP/R1BQKBNR w KQkq - 2 
checkers: h4
```

**Comment by lucasart** [comment]
I think we're ready to merge now:
* added getBoard() which is the opposite of setBoard(): compute FEN from board.
* display FEN in printBoard(): this adds the missing info (side to move, 50 move counter, castling rights, en passant square).
* fixed a stupid r/f inversion bug in stringToSquare()

**Comment by AndyGrant** [comment]
* I try my best to declare all variables at the top of a block, before anything else. Prior to merging your patches, all declarations were at the top of function blocks. But I'm trying to grow accustomed to doing it for loops and what not.

* Why use ``const int v`` over ``const int p`` in ``getBoard()``

* I tend to over comment things, but I think you under comment. I get a lot of email from people using Ethereal to understand how engines work, so I like to keep things overly clear when possible.

* ``uint64_t b = board->kingAttackers;`` I despise the way SF abuses the ever living hell out of `b` and `bb`. It makes figuring out a piece of code 10x longer, by forcing you to do all sorts of substitutions mentally. Call it checkers. 

* In the same function as above, we can just declare a single ``char str[256]`` at the top, and use that for both ``getBoard & squareToString``. 

* Do we gain anything by using ``sep`` instead of ``separator``?

* I'm starting to not even like all the ``r & f & c & s``.

* ``getBoard()`` sounds like some access method. How about ``getFenFromBoard(), boardToFen()``, ... . It should also be added to the header file

**Comment by lucasart** [comment]
> I try my best to declare all variables at the top of a block, before anything else. Prior to merging your patches, all declarations were at the top of function blocks. But I'm trying to grow accustomed to doing it for loops and what not.

What you're doing is very old fashion. It's based on a limitation from C89, which was lifted in C99 (and in C++). Nowadays, everyone is declaring variables where they are used. It makes code more readable, and helps keep code pieces independent (with zero performance cost).

> Why use const int v over const int p in getBoard()

Agree. Renamed.

> I tend to over comment things, but I think you under comment. I get a lot of email from people using Ethereal to understand how engines work, so I like to keep things overly clear when possible.

I prefer to make the code self-documenting, than to comment for the sake of commenting. Feel free to edit the patch and add comments where you think it's necessary.

> uint64_t b = board->kingAttackers; I despise the way SF abuses the ever living hell out of b and bb. It makes figuring out a piece of code 10x longer, by forcing you to do all sorts of substitutions mentally. Call it checkers.

I would agree with you if `checkers` was const. But it's being consumed by the while loop. So it's a loop counter. Just like it's idiomatic to use `i` as int loop counter, it's idiomatic to use `b` for bitboard loop counters.

> In the same function as above, we can just declare a single char str[256] at the top, and use that for both getBoard & squareToString.

I think that's bad taste. The two buffers have different sizes, and purposes. And I want code pieces to be independent, no dependence on what's 1 page of code above (variable declarations). The compiler will probably mutualise the two buffers and do what you say.

> Do we gain anything by using sep instead of separator?

Agree. Renamed.

> I'm starting to not even like all the r & f & c & s.

What do you want instead ? `rank, file, colour, square` ? Or `rk, fl, col, sq` ?

> getBoard() sounds like some access method. How about getFenFromBoard(), boardToFen(), ... . It should also be added to the header file

Agree. Renamed to boardToFEN(). And, for consistency, renamed setBoard() to boardFromFEN(). I'm keeping FEN in capital letters, because it's an acronym, like SEE, PGN, etc.

**Comment by AndyGrant** [comment]
> I would agree with you if checkers was const. But it's being consumed by the while loop. So it's a loop counter. Just like it's idiomatic to use i as int loop counter, it's idiomatic to use b for bitboard loop counters.

That is a very good point -- had not thought of that this way.

> What do you want instead ? rank, file, colour, square ? Or rk, fl, col, sq ?

Lets just keep going as is for now. I think I'm just going crazy. 

> I prefer to make the code self-documenting, than to comment for the sake of commenting. Feel free to edit the patch and add comments where you think it's necessary.

Same as above.

Are you ready for this to be merged?

As a side note, this is the first time I've ever had someone else committing code into one of my projects. I think for some reason I'm becoming defensive of the style Ethereal is written in, as some sort of way to "keep the project mine". But this should pass in time I hope.

**Comment by lucasart** [comment]
> Are you ready for this to be merged?

yes

**Comment by lucasart** [comment]
On the commenting, I think some commenting is good, but perhaps you're not doing it in the right places. Commenting is merely a means to an end: documentation.

Most of the time, the best way to document is to choose function and variable names that are self documenting.

As for the inner workings of the code (ie. the how rather than the what/why):
* commenting self-obvious code is pointless.
* commenting smelly code is also pointless. You're better off rewriting the smelly code to make it self documenting.

But there are things that deserve comments, which you're not commenting. For example, when I see `ZorbistKeys[32][SQUARE_NB]` in an API, I'm left clueless as to what the first parameter encoding might be (the second is self documenting, not the first). You can use comments. Or you can rewrite the code to make it self documenting: `ZobristKeys[COLOUR_NB][PIECE_NB][SQUARE_NB]` for piece placement, `ZobristEnpassant[FILE_NB]` for en passant, etc.

**Pull request merged**
