### PR TITLE
Bitboard code-style massage

### PR DESCRIPTION
**Pull request by lucasart**
No functional change.

### CODE REVIEW

**Comment by AndyGrant** [comment]
I like the assertion guards around File and Rank. For those two functions I do the open brace on the same line as the function header.

I've been against pragma once without really knowing much about it, just because I know it is not in the standard. But a quick glance at wiki shows that most everyone supports it, and it can speed up compilation a tad.

The enum certainly looks nice. But aside from that, what is the advantage here?

Also, I assume the compiler is smart enough to turn the  % FILE_NB into an and, and / FILE_NB into a shift?

**Comment by lucasart** [comment]
> I like the assertion guards around File and Rank. For those two functions I do the open brace on the same line as the function header.

Done

> I've been against pragma once without really knowing much about it, just because I know it is not in the standard. But a quick glance at wiki shows that most everyone supports it, and it can speed up compilation a tad.

if guards are purely academic nowadays. In reality every compiler supports pragma once, it makes things easier for the compiler, and makes the code a tad cleaner.

> The enum certainly looks nice. But aside from that, what is the advantage here?

The debugger will be able to print the enum name rather than its value.

> Also, I assume the compiler is smart enough to turn the % FILE_NB into an and, and / FILE_NB into a shift?

Yes, C compilers have been able to do that for at least 3 decades now. As long as the compiler can determine at compile time that it's a power of two.

**Comment by lucasart** [comment]
commit updated. please check.

**Comment by AndyGrant** [comment]
Looks good. Continue doing the if ()<space>{. I thought what I was doing was the K&R way, but I was recalling incorrectly. You cut out the trailing whitespace, which I have not done anywhere else. I know SF does that, and it seems to be accepted, so I will start doing that as well.

Also, maybe worth noting, I do a bizarre way of versioning. Ethereal's version number is always #commits / 100. I update ETHEREAL_VERSION in uci.h with each commit, and rebuild some binaries just so people can grab them easily... but anyway, no need to do either of those things. Just be aware that I have a different (bad?) system.

Merging.

**Pull request merged**
