### PR TITLE
Zobrist

### PR DESCRIPTION
**Pull request by lucasart**

### CODE REVIEW

**Comment by AndyGrant** [comment]
This breaks the pawn hash. pkhash needs to be a hash based only on King and Pawn positions.

**Comment by lucasart** [comment]
I see. you wanted to avoid a branch in applyMove.

**Comment by AndyGrant** [comment]
Some time ago I recall testing with branching, and saw slight speed losses. But much has changed since then, and perhaps you have a different approach.

**Comment by lucasart** [comment]
I removed the offending patch.

**Pull request closed without merging**
