### PR TITLE
Rewrite Knight and King attack generation

### PR DESCRIPTION
**Pull request by lucasart**
No functional change.

### CODE REVIEW

**Comment by lucasart** [comment]
Few comments and a question:
* `File()` and `Rank()` did not respect the usual case convention, which is `thisCase()` not `ThisCase()` for functions. Obviously `file()` and `rank()` would cause some name collision, so I chose instead `fileOf()` and `rankOf()` (which is also the same as SF and Demolito).
* You may wonder why `clearBit()` and `setBit()` do the same thing. The difference is in documentation and assert. `setBit()` will ensure that the bit is not already set, and `clearBit()` ensures that the bit is indeed set. The reason for this will become more apparent as I progress to `move.c`. Using safe primitives like this is a great way to catch bugs.
* Do you mind if I fuse `bitboards` and `bitutils` ? I don't understand the point of having two separate units, and find it mildly annoying to have to include 2 different files for things so trivial (I never know what's in which unit because there's no clear logic behind it).

**Comment by AndyGrant** [comment]
- Well they were macros until you changed them to functions of the same name :)
- I figured as much. Interested to see how you plan to use them.
- Have at it. No rhyme or reason to a good deal of the boiler plate 

You are doing ``function(uint64_t* bb)`` over ``function(uint64_t *bb)``, which is what I should have done. The ``poplsb()`` function could use the same change.

I wanted to say that I prefer square, rank, file, over s, r, f, but it would be painful to read that in some of these functions. I like the names to be fairly descriptive, but these three are trivial .. same with bb ..

I would prefer to not use bool, and just stick to int, unless you have a compelling argument for bool.

I like the magics cleanup. The King+Knight rewrite makes much more sense that what I had.

**Comment by AndyGrant** [comment]
Also, you may want to just merge with ``square.c & square.h`` as well.  The square unit has no reason to be logically separated from bitboards and bitutilities

**Comment by lucasart** [comment]
> You are doing function(uint64_t* bb) over function(uint64_t *bb), which is what I should have done. The poplsb() function could use the same change.

I don't understand. I don't see this in my code. The C idiom is `type *ptr` not `type* ptr`, and I always use the former.

> I wanted to say that I prefer square, rank, file, over s, r, f, but it would be painful to read that in some of these functions. I like the names to be fairly descriptive, but these three are trivial .. same with bb ..

This may sound like a good idea, but, in my experience, it just makes the code overly verbose with no benefit to readability. Even SF uses `s, r, f, b`, not `square, rank, file, bitboard`. The other problem is name collisions. If you use `rank` for variable, you can't use `rank()` and have to use `rankOf()`. Same for `file`. And same for `square`, you can't use `square()` but have to rename it to something like `makeSquare()`, etc.
I don't *generally* suggest to use 1 letter variable names, but there are idioms easily recognisable like: b = bitboard, s = square, r = rank, f = file, i = some counter for loops, j = some counter for inner loop, etc.
If you really want to be a tad more descriptice, may I suggest: `sq, rk, fl, bb` instead of `s, r, f, b` ?

> I would prefer to not use bool, and just stick to int, unless you have a compelling argument for bool.

There are 2 reasons for bool:
* documentation: the code is more self-obvious with bool/true/false, thant with int/0/1.
* avoid errors: bool will enforce 0/1 values under the hood. So you don't need to write things like `int several = !!(b & (b-1))`, but instead just `bool several = b & (b-1)`. If you're just using `several` in an `if` you don't care, but if you're going to index an array with it like with evaluation bonus depending on a bool parameter, this can be nice.

**Comment by AndyGrant** [comment]
https://github.com/AndyGrant/Ethereal/commit/80dea05f894221fbd215b884b62b3e7f8d592989#diff-a3b5b62f9d2a04e8cb3cebc40c1c896bR291

https://github.com/AndyGrant/Ethereal/commit/80dea05f894221fbd215b884b62b3e7f8d592989#diff-b678b685c25a4b9b9e6c265d5d691bf7R38

Is what I'm talking about. 

Any thoughts on bool vs int?

**Comment by lucasart** [comment]
Ah, I see it now:
```
static void getSetBits(uint64_t bb, int* arr) {

    int count = 0;

    while (bb)
        arr[count++] = poplsb(&bb);

    arr[count] = -1;
}
```
The reason I didn't touch or try to refactor this code, is because I'm going to get rid of it all in the next pull request, and rewrite all the magic bitboard stuff it in a much more direct and cleaner way.

**Comment by AndyGrant** [comment]
Okay, that sounds good. Do you want me to merge this, or let you do your unit merging?
Also, again, the bool? :)

**Comment by lucasart** [comment]
For bool I answered above (though I edited perhaps that's why you didn't see it).

Yes, please merge if ok for you.

**Comment by AndyGrant** [comment]
Seems petty, but is there any performance hit for "forcing 0/1 under the hood"?

**Comment by lucasart** [comment]
I really doubt there is any performance penalty. The compiler is able to inline several, and will see that if used in a if, the 0/1 conversion is useless. You can try to measure it, if you are skeptical.

**Comment by lucasart** [comment]
By the way, do you have a reliable way to make speed measures in Ethereal ?

**Comment by AndyGrant** [comment]
Usually the speedups I find are large enough that I don't need too reliable a testing setup. At some point I was using psybench ( or whatever SF folks were using at the time ).

**Pull request merged**
