### PR TITLE
Attempt to fix a bug causing search to return a move from an incomple…

### PR DESCRIPTION
**Pull request by Mk-Chan**
…te iteration

### CODE REVIEW

**Comment by AndyGrant** [comment]
I don't think we also want to throw out information from the incomplete search. Say we run out of time while searching depth 10. During that search we may have proven the current PV to be wrong, and another move (A) to be better. Even if we don't finish the search to prove A to be the best, we still know it is better than the PV.

**Comment by Mk-Chan** [comment]
That makes sense but in that case, the only way for that bug of your's to occur(where the score dropped from +4 to 0 in the game) was if the best move from your last iteration was not searched first, or if your engine felt the +0 line was better(which is unlikely), or if in that particular iteration, it couldn't see a winning line

**Comment by AndyGrant** [comment]
I think the issue is created during the aspiration windows. I need to sit
down and think about this, but it looks like a rootSearch with an
aspiration window can run out of time, return a Mate score, but then have
another rootSearch called, this time on the full window.

I need to track down that game where I saw it occur to be sure of the
solution.

Your patch will fix the bug, that's for sure. But in want to see if I can
salvage some of the incomplete search.

**Comment by Mk-Chan** [comment]
I think you should be fine returning the bestmove of an incomplete iteration if you've searched the bestmove of the previous iteration(and gotten the real value, not an aspiration window bound) at least. Because then if your bestmove gets replaced, you're sure that it's at least as good as your old PV. I think to implement that would mean you'd have completely searched the first move in the list in order to have confidence, if the first move is not searched, then return the previous iteration's bestmove.

**Comment by AndyGrant** [comment]
The way I see it, there are a couple of possible levels of information loss.

1) Throw everything from an incomplete depth search
2) Throw everything from an incomplete aspiration search
3) Throw nothing away

We can do 1) with your patch.
We can do 2) if we move your patch to include the aspiration window
We can do 3) if we take a better look at how we save move values

Alas, I don't have the time to find a solution for the time being. 

Don't take my inactivity on this pull request as being dismissive :)

**Comment by Mk-Chan** [comment]
That's ok, better to take the time to find a good solution. I don't think it should be a problem with aspiration windows but I wouldn't bet on it. Meanwhile I'll add the same to my program and try and see how I can effectively use incomplete iteration values.
Now that I think about it we could probably get a headstart on talkchess

**Comment by Mk-Chan** [comment]
This thread seems to have come to the same conclusion: http://talkchess.com/forum/viewtopic.php?t=61759

**Comment by AndyGrant** [comment]
Hmm, was reading that thread earlier.

It looks to like a resonable solution is the following.

1) Actually Track the PV
2) Instead of returning these bogus MATE scores, just declare some flag for timeExpired. After every call to a search, qSearch, alphaSearch, alpha search from IID / Null Move / Razoring, or whatever, check that flag before continuing the search. If that flag is ever true, just return until we get back to the main ID loop. 

If a complete search has finished the PV will be updated, otherwise the results of a partial search will never propagate back into the PV.

**Comment by Mk-Chan** [comment]
Yes, that's seems fine, I guess you can close this pull request now

**Comment by AndyGrant** [comment]
Further investigation found no issues with the current scheme. Additionally, when I tracked down the pgn form Graham's tournament, the game suddenly ended on the 80th move, the one where Ethereal 'screwed up'. It is my belief that Ethereal timed out, the gui choose a move at random, and the pgn ended when ethereal timed out, even though the rest of the game was played out.

A semi-recent patch fixed issues with 40 * Nth moves.

**Pull request closed without merging**
