### PR TITLE
Bench from command line

### PR DESCRIPTION
**Pull request by lucasart**
Ethereal now takes 2 (optional) parameters:
- ./Ethereal: run normally (UCI mode)
- ./Ethereal 14: run bench at depth=14 (default 1 thread)
- ./Ethereal 16 4: run bench with depth=16 and threads=4

Fix main() return value while at it (correct return value is zero to indicate no
error).

This allows to measure speed with far less noise, as we can get rid of stdout
printing (which causes lots of delays and randomness by itself). Also, we can
easily script bench (no need to write pipe connection scripts to just read a
bench measure).

Example ways to make reduced noise measures:
$ time ./Ethereal 13 > /dev/null  (measure process/system time)
$ ./Ethereal 13 | tail -3  (display time/nodes/nps)
$ ./Ethereal 13 |tail -1|cut -d\:  -f2  (display only nps)

### CODE REVIEW

**Comment by AndyGrant** [comment]
Will try this out when I get home this evening. Plan to merge. Thanks!

**Comment by lucasart** [comment]
Also, I suggest to change the position set for bench. SF one is handpicked and quite biaised. I recommend choosing random position from varied games, as we want a representative sample to make speed measures that are relevant.

**Comment by AndyGrant** [comment]
Feel free to choose some if you have something in mind. Otherwise I'll
extract from a few PGNs I have sitting around.

**Comment by lucasart** [comment]
Done.

**Comment by lucasart** [comment]
I compared gcc and clang speed on my machine, using depth=16 run (filtering stdout). Median of 5 runs:
* gcc = 3291357 NPS
* clang = 3149820 NPS

Indeed, GCC is 4.5% faster than Clang.

**Comment by AndyGrant** [comment]
Anything against making the command line argument the following...

``./Ethereal bench <depth> <threads>``

Increment the argc indxes by one, and quick check with ``1argc > 1 && strequals("bench", argv[1])``... but you already know that. 

I'd like to have "bench" there just to make it more clear.

This patch will let me simplify some stuff in my testing framework. Right now I open a sub process, send "bench 13", and read output till I get the nps -- clearly bad

**Comment by lucasart** [comment]
Will do.

While there, should I do the same for perft ?

**Comment by AndyGrant** [comment]
I'll say pass on the perft for now. I've been meaning to write a nice perft which prints each initial move, as well as make use of the threads. I'll get around to that one day -- maybe. Not very important to Ethereal, however.

**Pull request merged**
