### PR TITLE
Cleanup piece.h

### PR DESCRIPTION
**Pull request by lucasart**
Remove all macros, use instead:
- enum (for constants)
- safe functions (for assert checking)

### CODE REVIEW

**Comment by AndyGrant** [comment]
Will run this later this evening. I remember having issues with static functions in headers when using GCC, which was the initial reason for macros .

**Comment by lucasart** [comment]
I don't really like static inline functions in header files, to be honest. What I prefer instead is to avoid naked headers, and have piece.c with the function's implementation there, and leave only the declaration (ie. API) in the header.

But macros are evil. First the macro expansion is a textual replace, so it can lead to surprises (eg. if you write UglyMacro(i++), you really need to think about how it expands, and how many times i++ will be evaluated), and we also want assert bound checking, to save time debugging.

**Comment by AndyGrant** [comment]
You can delete
```
enum {
    PAWN_FLAG   =  0,
    KNIGHT_FLAG =  4,
    BISHOP_FLAG =  8,
    ROOK_FLAG   = 12,
    QUEEN_FLAG  = 16,
    KING_FLAG   = 20
};
```

Also, I hit the assert on line 44 when running the bench. I think we should be guarding 
with ``< PIECE_NB + 1`` to account for ``pieceType(EMPTY) and pieceColours(EMPTY)``.

Not quite sure how that should be denoted, as it looks strange to a viewer. 

I'll say that I am against static functions in headers, but I think I'm okay with those declared with ``inline``, as that removes the problem I used to have, so long as the compiler DOES the inline (Is this guaranteed?). Furthermore, if there exists a ``.c`` file for a header, then functions should go there. Alternatively, you could merge this with ``types.h`` (usually imported together anyway), and write a ``piece.c`` for the three functions.

**Comment by lucasart** [comment]
Using 'static inline' is the *only* way to implement a function in a header. Without static, you get a linker error if several compilation units include the same header, as it violates the single definition rule. The problem comes from C++, which gives people bad habits, by making inline functions compiled statically by default (for this reason).

Note that using inline never guarantees anything. It's merely a hint for the compiler. The only thing you should care about is the speed you can measure (let the compiler do its job, and judge the result, don't try to micro manage too much). In practice trivial functions like that will be inlined.

**Comment by lucasart** [comment]
how about now?

**Comment by AndyGrant** [comment]
Just to highlight how weird speed testing is .... I looked at the assembly dumps and as far as I can see the move application functions are identical (as you would expect).

```
andrew@ryzen:~/Desktop$ ./base bench 24 |tail -3
Time  : 167771ms
Nodes : 528162183
NPS   : 3148113
andrew@ryzen:~/Desktop$ ./base bench 24 |tail -3
Time  : 168301ms
Nodes : 528162183
NPS   : 3138199
andrew@ryzen:~/Desktop$ ./base bench 24 |tail -3
Time  : 165240ms
Nodes : 528162183
NPS   : 3196333
andrew@ryzen:~/Desktop$ ./base bench 24 |tail -3
Time  : 164227ms
Nodes : 528162183
NPS   : 3216049
andrew@ryzen:~/Desktop$ ./base bench 24 |tail -3
Time  : 166616ms
Nodes : 528162183
NPS   : 3169936
andrew@ryzen:~/Desktop$
```

```
andrew@ryzen:~/Desktop$ ./test bench 24 |tail -3
Time  : 167915ms
Nodes : 528162183
NPS   : 3145413
andrew@ryzen:~/Desktop$ ./test bench 24 |tail -3
Time  : 169384ms
Nodes : 528162183
NPS   : 3118135
andrew@ryzen:~/Desktop$ ./test bench 24 |tail -3
Time  : 165450ms
Nodes : 528162183
NPS   : 3192276
andrew@ryzen:~/Desktop$ ./test bench 24 |tail -3
Time  : 166667ms
Nodes : 528162183
NPS   : 3168966
andrew@ryzen:~/Desktop$ ./test bench 24 |tail -3
Time  : 166100ms
Nodes : 528162183
NPS   : 3179784
andrew@ryzen:~/Desktop$
```

**Comment by lucasart** [comment]
i know. bench measures are very noisy. that's why I always take the median of 5 runs.But even that is noisy. It's best to use pyshbench. It was designed explicitly for that. Given background noise that can't be killed, all we can do is make sure master/test share the same noise, so that test-master vector has an order of magnitude less noise.

**Pull request merged**
