### PR TITLE
Popcount safe checks

### PR DESCRIPTION
**Pull request by lucasart**
STC 10+0.1
LLR: 3.00 (-2.94, 2.94) [0.00, 5.00]
Games: 37330 W: 7995 L: 7685 D: 21650

LTC 60+0.6
LLR: 2.96 (-2.94, 2.94) [0.00, 5.00]
Games: 5730 W: 982 L: 838 D: 3910

bench 5797699

### CODE REVIEW

**Comment by AndyGrant** [comment]
In ``uci.h`` go kick up the version number to ``11.09``

**Comment by lucasart** [comment]
> Ethereal will still use a static evaluation for in check positions.

Weird. Have you tried doing it the normal way and found it lost elo ? (ie. handle in search such that eval never calculates a checked position)

**Comment by AndyGrant** [comment]
I have tried this a few times. It has always lost elo, I suspect because the removal of FutilityPruning when in check. However, SEE() pruning might be new since then, so perhaps now the standard way will work.

**Comment by lucasart** [comment]
> In uci.h go kick up the version number to 11.09

Done

**Pull request merged**
