### PR TITLE
Aspiration window change

### PR DESCRIPTION
**Pull request by robertomil81mil**
In the case of a fail high research with an adjusted depth.

Andrew can you test this?

Thanks.

### CODE REVIEW

**Comment by AndyGrant** [comment]
I have launched two initial tests, found [here](http://chess.grantnet.us/viewTest/4034/) and [here](http://chess.grantnet.us/viewTest/4033/)

I suggested to you that there is a risk of an infinite recursion. I have since noticed that as we continually increase the window size, the number of searches we do is bounded.

The 2nd link is more similar to what you wanted to see, although not the same as what you had done. I believe you wanted to not reset the counter on fail-highs, but reduce it by 1 when applicable. In your code, you would look for the FIRST non-fail low search of any depth in order to exit. IE, in the worst case, with 20 consecutive fail lows on a depth 20 search, if the depth 1 search returns inside the window (likely), it returns. 

I will look to play with the window size and the increment applied to the window. Changing the start depth for the window is more or less a non-factor.

**Comment by robertomil81mil** [comment]
you caught it, Thanks Andrew. That's the idea.

**Comment by AndyGrant** [comment]
Those tests did not pass. Do you have any other variations or suggestions for the idea? Happy to test most things you might suggest. Otherwise, I'll leave this issue open for a bit in case I come up with some variants before closing it.

**Comment by robertomil81mil** [comment]
Ok, I know, I'll try someting, Thanks.

**Comment by AndyGrant** [comment]
https://github.com/AndyGrant/Ethereal/commit/710f64e10d0866b18d9584b1dcb1f85eb7d93611 resolved

**Pull request closed without merging**
