### PR TITLE
printBitboard()

### PR DESCRIPTION
**Pull request by lucasart**
Useful for debugging.

Simplify printBoard() while at it. No need to get too fancy with ASCII art, it's
just for debugging.

### CODE REVIEW

**Comment by lucasart** [comment]
I found a bug while testing my code. Your FEN parser initializeBoard() is not read en-passant square. To reproduce, instrument the code to print fen and epsq at the end of the function, and you should see:
```
position fen rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 1
fen=rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 1
epsq=-1
```
Unrelated to this pull request, and will be fixed separately, when I rewrite the FEN parser.

**Comment by AndyGrant** [comment]
Happy with printBitboard. I'm not interested in changing the ``printBoard`` function, aside from printing the enpass square, castling rights, and the side to move.

As for the enpass parsing .... whoops. UCI always uses the move lists so I suppose I never really find myself parsing fens with enpass in them.

**Comment by lucasart** [comment]
How about now ? Example:
```
  |---|---|---|---|---|---|---|---|
8 | r | n | b | q | k | b | n | r |
  |---|---|---|---|---|---|---|---|
7 | p | p | p | p | p | p | p | p |
  |---|---|---|---|---|---|---|---|
6 | . | . | . | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
5 | . | . | . | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
4 | . | . | . | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
3 | . | . | . | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
2 | P | P | P | P | P | P | P | P |
  |---|---|---|---|---|---|---|---|
1 | R | N | B | Q | K | B | N | R |
  |---|---|---|---|---|---|---|---|
    A   B   C   D   E   F   G   H
```

**Comment by AndyGrant** [comment]
Okay. Happy medium. Simpler than what I have, but still more than good enough for debug. 

Ill merge this in the morning. Thank you for these PRs.

**Pull request merged**
