### PR TITLE
printMove() -> moveToString()

### PR DESCRIPTION
**Pull request by lucasart**

### CODE REVIEW

**Comment by AndyGrant** [comment]
In ``board.c``, lets move ``const char *PieceLabel[COLOUR_NB] = {"PNBRQK", "pnbrqk"};`` before my list of positions.

In ``move.c::moveToString()`` do you not want to set ``str[4] = '\0'`` for non promotions?

Throughout I prefer to not use ``puts()``, and use ``printf("%s\n", str);``

I just removed two lines from ``uci.c`` in my last patch, so making this merge-able should be easy.

You closed the Zobrist PR. Do you want to put the rename in this patch?

I'm going to do a big release at 10.00 (1,000 commits) for the two year anniversary, fyi.

Thanks!

**Comment by lucasart** [comment]
> In board.c, lets move const char *PieceLabel[COLOUR_NB] = {"PNBRQK", "pnbrqk"}; before my list of positions.

Done, along with removing NUM_BENCHMARKS. Instead, it's discovered as we loop across the array. Makes the code flexible (ie. just add/remove strings from Benchmarks[], nothing to change).

> In move.c::moveToString() do you not want to set str[4] = '\0' for non promotions?

This is taken care of by squareToString().

> Throughout I prefer to not use puts(), and use printf("%s\n", str);

puts() is the most straightforward way to print a string. Instead, I find printf("%s\n", str) quite convoluted. And significantly slower (because it has a lot more work to do, implementing printf() from scratch is not simple). So it seems to me that the good habit is to use puts() and only printf() when you need to.

> You closed the Zobrist PR. Do you want to put the rename in this patch ?

Yes. Well there was not much point. A more worthy patch would be to completely redesign the Zobrist logic, perhaps along with FRC. But that's a bit more work.

**Comment by AndyGrant** [comment]
I still want ``printf("%s\n", str)`` over ``puts(str)``. The speed of printf / uci reporting is not a concern. Otherwise I would limit that further. For consistency I prefer printf.

I like everything else. I had ``#define NUM_BENCHMARKS`` because it worked at the time, but that was clearly awful looking. Your solution is much nicer. And, as you said, we can easily add more / FRC positions to that. Although FRC might take a little more thought.

**Comment by AndyGrant** [comment]
Screw it. I changed my mind.

**Pull request merged**
